### ISSUE TITLE
get_encoders() got an unexpected keyword argument 'use_adapter'

### ISSUE THREAD

**Issue by fb1018** [weizhepei/HBT#54]
Traceback (most recent call last):
  File "run.py", line 40, in <module>
    subject_model, object_model, hbt_model = E2EModel(bert_config_path, bert_checkpoint_path, LR, num_rels)
  File "/home/fubo01/work/paper/CasRel/CasRel-master/model.py", line 15, in E2EModel
    bert_model = load_trained_model_from_checkpoint(bert_config_path, bert_checkpoint_path, seq_len=None)
  File "/home/fubo01/miniconda3/envs/CasRel/lib/python3.7/site-packages/keras_bert/loader.py", line 169, in load_trained_model_from_checkpoint
    **kwargs)
  File "/home/fubo01/miniconda3/envs/CasRel/lib/python3.7/site-packages/keras_bert/loader.py", line 58, in build_model_from_config
    **kwargs)
  File "/home/fubo01/miniconda3/envs/CasRel/lib/python3.7/site-packages/keras_bert/bert.py", line 126, in get_model
    adapter_activation=gelu,
TypeError: get_encoders() got an unexpected keyword argument 'use_adapter'

**Comment by fb1018** [comment]
please release your requirements.txt!!!! OK ?

**Comment by jiaruncao** [comment]
I solved this problem by installing keras-transformer==0.30.0 via pip.

**Comment by jiaruncao** [comment]
> please release your requirements.txt!!!! OK ?

I solved this problem by installing keras-transformer==0.30.0 via pip.

**Comment by GoodDayUp** [comment]
pip install keras_bert==0.81.1
