### ISSUE TITLE
运行run.py文件时显示tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files

### ISSUE THREAD

**Issue by tyty19701998** [weizhepei/HBT#70]
Traceback (most recent call last):
  File "e:\code1\CasRel-master\run.py", line 57, in <module>
    hbt_model.load_weights(save_weights_path)
  File "C:\Users\t't't\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\t't't\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\training\py_checkpoint_reader.py", line 31, in error_translator
    raise errors_impl.NotFoundError(None, None, error_message)
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for saved_weights/NYT/best_model.weights
运行run.py文件时报错，显示无法找到该文件，请问best_model.weights文件是如何生成的

**Comment by zhangzy0828** [comment]
> Traceback (most recent call last): File "e:\code1\CasRel-master\run.py", line 57, in hbt_model.load_weights(save_weights_path) File "C:\Users\t't't\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler raise e.with_traceback(filtered_tb) from None File "C:\Users\t't't\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\training\py_checkpoint_reader.py", line 31, in error_translator raise errors_impl.NotFoundError(None, None, error_message) tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for saved_weights/NYT/best_model.weights 运行run.py文件时报错，显示无法找到该文件，请问best_model.weights文件是如何生成的

你好，请问解决了吗，我也遇到相同的问题，大佬求解答

**Comment by 32209056** [comment]
同问，请问解决了吗

**Comment by youngsasa2021** [comment]
同问
