### ISSUE TITLE
I followed the instructions in the README exactly, but I'm getting this error when running "python run.py --train=True --dataset=NYT". Can anyone tell me how to fix it? I appreciate any help! My environment has been modified according to everyone's suggestions.

### ISSUE THREAD

**Issue by rabbitlingli** [weizhepei/HBT#84]
(CasRel) yons@jmw-lab-server:~/lilinglicode/CasRel$ `python run.py ---train=True --dataset=NYT`
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/yons/anaconda3/envs/CasRel/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/yons/anaconda3/envs/CasRel/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/yons/anaconda3/envs/CasRel/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/yons/anaconda3/envs/CasRel/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/yons/anaconda3/envs/CasRel/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcudnn.so.7: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from model import E2EModel, Evaluate
  File "/home/yons/lilinglicode/CasRel/model.py", line 2, in <module>
    from keras.layers import *
  File "/home/yons/anaconda3/envs/CasRel/lib/python3.7/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/home/yons/anaconda3/envs/CasRel/lib/python3.7/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/home/yons/anaconda3/envs/CasRel/lib/python3.7/site-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/home/yons/anaconda3/envs/CasRel/lib/python3.7/site-packages/keras/backend/__init__.py", line 1, in <module>
    from .load_backend import epsilon
  File "/home/yons/anaconda3/envs/CasRel/lib/python3.7/site-packages/keras/backend/load_backend.py", line 89, in <module>
    from .tensorflow_backend import *
  File "/home/yons/anaconda3/envs/CasRel/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "/home/yons/anaconda3/envs/CasRel/lib/python3.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/yons/anaconda3/envs/CasRel/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/yons/anaconda3/envs/CasRel/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/yons/anaconda3/envs/CasRel/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/yons/anaconda3/envs/CasRel/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/yons/anaconda3/envs/CasRel/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/yons/anaconda3/envs/CasRel/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/yons/anaconda3/envs/CasRel/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcudnn.so.7: cannot open shared object file: No such file or directory

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
(CasRel) yons@jmw-lab-server:~/lilinglicode/CasRel$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243

My understanding is whether my CUDA version being 11.4 might be causing issues since others have suggested using CUDA 10.0.？？

**Comment by rabbitlingli** [comment]
Resolved, following the #66 environment debugging approach, has been resolved.
